# Generated by Django 4.0.1 on 2022-07-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('cpnumber', models.DecimalField(decimal_places=0, default='', max_digits=11)),
                ('gender', models.CharField(default='', max_length=6)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('section', models.CharField(default='', max_length=20)),
                ('field', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='PENDING', max_length=10)),
            ],
        ),
    ]
