# Generated by Django 4.0.1 on 2022-07-31 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('idnumber', models.CharField(default='', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('cpnumber', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=6)),
                ('age', models.CharField(default='', max_length=3, null=True)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('section', models.CharField(default='', max_length=20)),
                ('field', models.CharField(default='', max_length=20)),
                ('picture', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('civil', models.CharField(default='', max_length=20)),
                ('nfather', models.CharField(default='', max_length=20)),
                ('foccupation', models.CharField(default='', max_length=20)),
                ('nmother', models.CharField(default='', max_length=20)),
                ('moccupation', models.CharField(default='', max_length=20)),
                ('pcontact', models.CharField(default='', max_length=20)),
                ('nguardian', models.CharField(default='', max_length=20)),
                ('goccupation', models.CharField(default='', max_length=20)),
                ('gcontact', models.CharField(default='', max_length=20)),
                ('idpic', models.ImageField(default='', null=True, upload_to='images/')),
                ('disease', models.CharField(default='', max_length=100)),
                ('specific', models.CharField(default='', max_length=100)),
                ('proof', models.FileField(default='', upload_to='proofs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
