# Generated by Django 4.1.1 on 2022-10-14 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=20)),
                ('content', models.CharField(default='', max_length=500)),
                ('date_posted', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year2', models.CharField(default='', max_length=20)),
                ('commandant', models.CharField(default='', max_length=40)),
                ('registrar', models.CharField(default='', max_length=40)),
                ('month', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('acts', models.CharField(default='PENDING', max_length=20)),
                ('date_generated', models.DateTimeField(null=True)),
                ('commandant', models.CharField(default='', max_length=20)),
                ('registrar', models.CharField(default='', max_length=20)),
                ('month', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('fiel', models.CharField(default='', max_length=20)),
                ('section_created', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='training_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.DateField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30, null=True)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('middlename', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('idnumber', models.CharField(default='', max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('cpnumber', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=6)),
                ('age', models.CharField(default='', max_length=3, null=True)),
                ('birthday', models.CharField(default='', max_length=15)),
                ('section', models.CharField(default='', max_length=20)),
                ('field', models.CharField(default='Select Course', max_length=20)),
                ('picture', models.ImageField(upload_to='images/')),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('platoons', models.CharField(default='PROCESSING', max_length=20)),
                ('civil', models.CharField(default='', max_length=20)),
                ('nfather', models.CharField(default='', max_length=20)),
                ('foccupation', models.CharField(default='', max_length=20)),
                ('nmother', models.CharField(default='', max_length=20)),
                ('moccupation', models.CharField(default='', max_length=20)),
                ('pcontact', models.CharField(default='', max_length=20)),
                ('nguardian', models.CharField(default='', max_length=20)),
                ('goccupation', models.CharField(default='', max_length=20)),
                ('gcontact', models.CharField(default='', max_length=20)),
                ('idpic', models.ImageField(default='', upload_to='images/')),
                ('disease', models.CharField(default='', max_length=100)),
                ('specific', models.CharField(default='', max_length=100)),
                ('proof', models.FileField(default='', upload_to='proofs/')),
                ('s_year', models.CharField(default='0000', max_length=100)),
                ('TD1', models.CharField(default='', max_length=100)),
                ('TD2', models.CharField(default='', max_length=100)),
                ('TD3', models.CharField(default='', max_length=100)),
                ('TD4', models.CharField(default='', max_length=100)),
                ('TD5', models.CharField(default='', max_length=100)),
                ('TD6', models.CharField(default='', max_length=100)),
                ('TD7', models.CharField(default='', max_length=100)),
                ('TD8', models.CharField(default='', max_length=100)),
                ('TD9', models.CharField(default='', max_length=100)),
                ('TD10', models.CharField(default='', max_length=100)),
                ('TD11', models.CharField(default='', max_length=100)),
                ('TD12', models.CharField(default='', max_length=100)),
                ('TD13', models.CharField(default='', max_length=100)),
                ('TD14', models.CharField(default='', max_length=100)),
                ('TD15', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
