# Generated by Django 4.1.2 on 2022-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='equivalent_merits',
            field=models.CharField(default='30.00', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='equivalent_merits2',
            field=models.CharField(default='30.00', max_length=20),
        ),
    ]
