# Generated by Django 4.1.1 on 2023-01-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='staff_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
