# Generated by Django 4.1.1 on 2022-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
