# Generated by Django 4.1.4 on 2022-12-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
