# Generated by Django 4.1.1 on 2022-10-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_day',
            name='td_count',
            field=models.CharField(default='', max_length=254),
        ),
    ]
