# Generated by Django 4.0.1 on 2022-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='idnumber',
            field=models.CharField(default='', max_length=30),
        ),
    ]
