# Generated by Django 4.0.1 on 2023-01-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
