# Generated by Django 4.1.2 on 2022-12-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='nationality',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='note',
            field=models.CharField(default='', max_length=20),
        ),
    ]
