# Generated by Django 4.0.1 on 2022-07-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='idpic',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
