# Generated by Django 4.1.2 on 2022-11-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='all_act_score',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='all_act_score2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
