# Generated by Django 4.0.1 on 2022-07-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='civil',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='foccupation',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='gcontact',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='goccupation',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='idpic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='moccupation',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='nfather',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='nguardian',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='nmother',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='pcontact',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='section',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
