# Generated by Django 4.1.1 on 2022-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='date_generated',
            field=models.DateTimeField(default='PENDING', null=True),
        ),
    ]
