# Generated by Django 4.1.2 on 2022-12-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_extenduser_nationality_extenduser_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
