# Generated by Django 4.1.2 on 2022-12-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_extenduser_abs2_extenduser_pres2'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='percentage1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='percentage2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
