# Generated by Django 4.1.1 on 2022-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_school_year_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
    ]
