# Generated by Django 4.1.2 on 2022-11-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_extenduser_all_act_score_extenduser_all_act_score2'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(default='', upload_to='all_files/')),
            ],
        ),
    ]
