# Generated by Django 4.1.1 on 2023-01-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_extenduser_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='staff_status',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
