# Generated by Django 4.1.1 on 2022-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_training_day_td_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_day',
            name='td',
            field=models.DateField(blank=True, null=True),
        ),
    ]
