# Generated by Django 4.0.1 on 2022-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0002_extenduser_civil_extenduser_foccupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='age',
            field=models.CharField(default='None', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birthday',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='cpnumber',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='field',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='gender',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
