# Generated by Django 4.0.1 on 2023-01-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_extenduser_action_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='action_by',
        ),
        migrations.AddField(
            model_name='feedback',
            name='action_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
