# Generated by Django 4.1.1 on 2022-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_training_day_td'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_year',
            name='status',
        ),
        migrations.AddField(
            model_name='school_year',
            name='sem',
            field=models.CharField(default='1s Sem', max_length=20),
        ),
    ]
