# Generated by Django 4.0.1 on 2022-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_extenduser_idpic_alter_extenduser_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='idpic',
            field=models.ImageField(default='../../mysite/nstpapp/static/images/tup.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='proof',
            field=models.FileField(default='../../mysite/nstpapp/static/images/tup.png', upload_to='proofs/'),
        ),
    ]
