# Generated by Django 4.1.1 on 2022-09-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_school_year_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='acts',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
