# Generated by Django 4.0.1 on 2022-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_extenduser_address_alter_extenduser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='age',
            field=models.CharField(default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='birthday',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='civil',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='cpnumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='field',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='foccupation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='gcontact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='goccupation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='moccupation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='nfather',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='nguardian',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='nmother',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='pcontact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='section',
            field=models.CharField(default='', max_length=20),
        ),
    ]
