# Generated by Django 4.1.1 on 2023-01-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_alter_extenduser_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwts_grading',
            name='attendance1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='exercises1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='final_exam1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='midterm_exam1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='participation1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='quiz1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cwts_grading',
            name='total1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
