# Generated by Django 4.1.2 on 2022-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_extenduser_percentage1_extenduser_percentage2'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='proof',
            field=models.FileField(default='', upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='sickness',
            field=models.CharField(default='', max_length=100),
        ),
    ]
