# Generated by Django 4.1.2 on 2022-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0003_csv_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_td', models.DateField(blank=True, null=True)),
                ('td_count', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
