# Generated by Django 4.0.1 on 2023-01-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_remove_extenduser_action_by_feedback_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='approved_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
