# Generated by Django 4.1.2 on 2022-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_cwts_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(default='', max_length=100)),
                ('final_exam', models.CharField(default='', max_length=100)),
                ('quiz', models.CharField(default='', max_length=100)),
                ('exercises', models.CharField(default='', max_length=100)),
                ('participation', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
