# Generated by Django 4.1.2 on 2022-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_cwts_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='acts_2',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
