# Generated by Django 4.1.2 on 2022-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_extenduser_proof_extenduser_sickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='proof',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
