# Generated by Django 4.1.1 on 2022-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_remove_school_year_status_school_year_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='sem',
            field=models.CharField(default='1st Sem', max_length=20),
        ),
    ]
