# Generated by Django 4.1.1 on 2022-09-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0004_school_year_acts'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandant', models.CharField(default='', max_length=20)),
                ('registrar', models.CharField(default='', max_length=20)),
                ('month', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
