# Generated by Django 4.1.2 on 2022-11-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_cwts_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwts_grading',
            name='midterm_exam',
            field=models.CharField(default='', max_length=100),
        ),
    ]
