# Generated by Django 4.1.1 on 2022-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='commandant',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_year',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_year',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_year',
            name='registrar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school_year',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
