# Generated by Django 4.1.2 on 2022-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_school_year_acts_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cwts_school_year',
        ),
        migrations.AddField(
            model_name='school_year',
            name='date_generated_2',
            field=models.DateTimeField(null=True),
        ),
    ]
