# Generated by Django 4.0.1 on 2023-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_extenduser_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='action_date',
            field=models.DateTimeField(null=True),
        ),
    ]
