# Generated by Django 4.1.1 on 2022-10-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0005_alter_school_year_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
