# Generated by Django 4.1.1 on 2022-10-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_school_year_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='att_credits',
            field=models.CharField(default='', max_length=100),
        ),
    ]
