# Generated by Django 4.1.1 on 2022-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_school_year_commandant_school_year_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='school_year2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
