# Generated by Django 4.0.1 on 2023-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_feedback_action_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='date_declined',
            field=models.DateTimeField(null=True),
        ),
    ]
