# Generated by Django 4.1.2 on 2022-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_cwts_grading_midterm_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwts_grading',
            name='total',
            field=models.CharField(default='', max_length=100),
        ),
    ]
