# Generated by Django 4.1.2 on 2022-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0006_delete_cwts_school_year_school_year_date_generated_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year2', models.CharField(default='', max_length=20)),
                ('commandant', models.CharField(default='', max_length=40)),
                ('registrar', models.CharField(default='', max_length=40)),
                ('month', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
