# Generated by Django 4.1.1 on 2023-01-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0007_extenduser_date_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='modified_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
