# Generated by Django 4.1.1 on 2023-01-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0008_extenduser_date_modified_extenduser_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='generate_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
