# Generated by Django 4.1.2 on 2022-11-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0008_cwts_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_count', models.CharField(default='', max_length=100)),
                ('act_title', models.CharField(default='', max_length=100)),
                ('act_numbers', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
