# Generated by Django 4.1.1 on 2022-10-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0008_extenduser_act1_extenduser_act2_extenduser_act3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_count', models.CharField(default='', max_length=100)),
                ('act_title', models.CharField(default='', max_length=100)),
                ('act_numbers', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
