# Generated by Django 4.1.2 on 2022-12-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0008_cwts_school_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cwts_school_year',
        ),
    ]
