# Generated by Django 4.1.1 on 2022-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0009_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_day',
            name='td',
            field=models.CharField(default='', max_length=254),
        ),
    ]
