# Generated by Django 4.1.2 on 2022-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0009_delete_cwts_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=50)),
                ('files', models.FileField(default='', upload_to='all_files/')),
            ],
        ),
        migrations.CreateModel(
            name='rotc_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='', max_length=50)),
                ('files', models.FileField(default='', upload_to='all_files/')),
            ],
        ),
    ]
