# Generated by Django 4.1.1 on 2023-01-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0009_school_year_generate_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_year',
            name='generate_by2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
