# Generated by Django 4.0.1 on 2022-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0010_alter_extenduser_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='field',
            field=models.CharField(default='Select Course', max_length=20),
        ),
    ]
