# Generated by Django 4.1.2 on 2022-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0010_extenduser_exe1_extenduser_exe10_extenduser_exe10_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_midterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('items', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
