# Generated by Django 4.1.1 on 2022-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0010_alter_training_day_td'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_day',
            name='td',
            field=models.DateField(blank=True, null=True),
        ),
    ]
