# Generated by Django 4.1.2 on 2022-12-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0010_cwts_files_rotc_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rotc_files',
            new_name='cfiles',
        ),
        migrations.RenameModel(
            old_name='cwts_files',
            new_name='rfiles',
        ),
    ]
