# Generated by Django 4.0.1 on 2022-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_alter_extenduser_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='firstname',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
