# Generated by Django 4.1.2 on 2022-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_alter_training_day_td'),
    ]

    operations = [
        migrations.CreateModel(
            name='midterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=45)),
                ('items', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
