# Generated by Django 4.1.2 on 2022-12-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_rename_rotc_files_cfiles_rename_cwts_files_rfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfiles',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rfiles',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
