# Generated by Django 4.1.1 on 2022-09-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_alter_school_year_date_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='date_generated',
            field=models.DateField(default='Not yet Done', max_length=40),
        ),
    ]
