# Generated by Django 4.1.2 on 2022-11-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0011_cwts_midterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwts_finals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('items', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
