# Generated by Django 4.1.2 on 2022-11-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0012_cwts_finals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cwts_finals',
            new_name='cwts_final',
        ),
    ]
