# Generated by Django 4.1.2 on 2022-10-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0012_midterm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midterm',
            old_name='sem',
            new_name='semester',
        ),
    ]
