# Generated by Django 4.1.2 on 2022-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0012_cfiles_date_posted_rfiles_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfiles',
            name='platoons',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rfiles',
            name='platoons',
            field=models.CharField(default='', max_length=50),
        ),
    ]
