# Generated by Django 4.1.2 on 2022-12-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0013_cfiles_platoons_rfiles_platoons'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumni_school_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
