# Generated by Django 4.0.1 on 2022-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0013_alter_extenduser_idpic_alter_extenduser_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='platoons',
            field=models.CharField(default='', max_length=20),
        ),
    ]
