# Generated by Django 4.1.2 on 2022-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0013_rename_cwts_finals_cwts_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_year',
            name='sem',
            field=models.CharField(default='First Term', max_length=20),
        ),
    ]
