# Generated by Django 4.1.2 on 2022-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0013_rename_sem_midterm_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midterm',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
