# Generated by Django 4.0.1 on 2022-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0014_extenduser_platoons'),
    ]

    operations = [
        migrations.CreateModel(
            name='sy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
