# Generated by Django 4.0.1 on 2022-08-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0015_sy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sy',
            new_name='school_year',
        ),
    ]
