# Generated by Django 4.0.1 on 2022-08-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0016_rename_sy_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='s_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
