# Generated by Django 4.1.2 on 2022-10-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0017_extenduser_act1_2_extenduser_act2_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='final_grade_2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
