# Generated by Django 4.0.1 on 2022-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0018_alter_extenduser_s_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='user_last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
