# Generated by Django 4.1.2 on 2022-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0019_extenduser_td10_2_extenduser_td11_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('items', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
