# Generated by Django 4.0.1 on 2022-08-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0020_remove_extenduser_user_last_seen_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
    ]
