# Generated by Django 4.1.2 on 2022-10-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0021_extenduser_first_equivalents_extenduser_first_merits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='TD10_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD11_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD12_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD13_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD14_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD15_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD1_2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD1_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD2_2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD3_2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD3_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD4_2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD4_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD5_2_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD5_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD6_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD7_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD8_dem',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD9_dem',
            field=models.CharField(default='', max_length=100),
        ),
    ]
