# Generated by Django 4.0.1 on 2022-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0021_delete_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_created', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
