# Generated by Django 4.0.1 on 2022-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0022_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_created', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
