# Generated by Django 4.0.1 on 2022-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0023_training_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_day',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
