# Generated by Django 4.0.1 on 2022-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0024_training_day_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=20)),
                ('content', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
