# Generated by Django 4.0.1 on 2022-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0027_alter_announcement_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_day',
            name='day_created',
            field=models.DateTimeField(default=''),
        ),
    ]
