# Generated by Django 4.0.1 on 2022-09-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0028_alter_training_day_day_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='TD1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD11',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD12',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD13',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD14',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD15',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD6',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD7',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='TD9',
            field=models.CharField(default='', max_length=100),
        ),
    ]
