# Generated by Django 4.0.1 on 2022-09-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpapp', '0030_alter_training_day_day_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_day',
            name='day_created',
        ),
    ]
